name: city_guide
description: City Guide MVP with favorites, maps deeplink, categories, i18n, near-me, submissions, cache
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^16.2.0
  shared_preferences: ^2.2.3
  http: ^1.5.0
  url_launcher: ^6.3.2
  intl: ^0.20.2
  geolocator: ^14.0.2
  path_provider: ^2.1.5
  dio: ^5.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/data/places.json
    - assets/data/events.json
    - assets/images/
